# fly.toml file generated for proud-surf-9953 on 2022-06-01T19:15:57-06:00

app = "proud-surf-9953"

kill_signal = "SIGINT"
kill_timeout = 5

[processes]
app = "bin/server"
worker = "bin/worker"

[env]
  APP_DOMAIN = "offline.pink"
  FORCE_SSL = true
  LUCKY_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "bin/tasks db.migrate"

[[services]]
  internal_port = 3001
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  # [[services.http_checks]]
  #   interval = 60000 # 1 minute
  #   grace_period = "1s"
  #   method = "get"
  #   path = "/ping"
  #   protocol = "http"
  #   restart_limit = 1
  #   timeout = 1000
  #   tls_skip_verify = false
  #   [services.http_checks.headers]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
