# fly.toml file generated for offline-pink on 2022-05-18T14:39:25-06:00

app = "offline-pink"

kill_signal = "SIGINT"
kill_timeout = 5

[processes]
app = "bin/server"
worker = "bin/worker"

[env]
  APP_DOMAIN = "offline-pink.fly.dev"
  FORCE_SSL = true
  LUCKY_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "bin/tasks db.migrate"

[[services]]
  http_checks = []
  internal_port = 3001
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
