version: 2
jobs:
  build:
    docker:
      - image: robacarp/amber_build:latest
    steps:
      - checkout
      - run: shards install
      - run: shards build offline_pink worker
      - save_cache:
          key: vi-{{ checksum shard.lock }}
          paths:
            - .shards
            - lib
