#!/bin/bash

source script/helpers/build_details.sh

echo build_timestamp="$build_timestamp"
echo git_rev="$git_rev"
echo git_tag="$git_tag"

# --platform linux/arm64,linux/amd64 \

docker buildx build . \
  --load \
  --platform linux/arm64 \
  --progress plain \
  -t offline_pink \
  --build-arg build_timestamp="$build_timestamp" \
  --build-arg git_rev="$git_rev" \
  --build-arg git_tag="$git_tag"
