#!/bin/bash

source script/helpers/build_details.sh

# docker tag offline_pink registry.fly.io/offline-pink
# docker push registry.fly.io/offline-pink
fly deploy \
  --remote-only \
  --build-arg build_timestamp="$build_timestamp" \
  --build-arg git_rev="$git_rev" \
  --build-arg git_tag="$git_tag"
