#!/bin/bash

set -evuo pipefail

# docker tag offline_pink registry.heroku.com/offline-pink/web
# docker push registry.heroku.com/offline-pink/web

# docker tag offline_pink registry.heroku.com/offline-pink/worker
# docker push registry.heroku.com/offline-pink/worker

# heroku container:release web worker

# heroku run bin/tasks db.migrate

docker tag offline_pink registry.fly.io/offline-pink
docker push registry.fly.io/offline-pink
fly deploy -i offline_pink
