#!/bin/sh

case "${1:-}" in
  "") # no arguments, start server
    ;;

  "worker")
    echo "Starting worker"
    exec /app/bin/worker
    ;;

  *)
    echo "Execing ${*}"
    exec "$@"
esac

echo "Starting server"
exec /crystal-build/bin/server
#exec /app/bin/server
