secret_key_base: 2LMqiWnO_adAJy6kaFZZ2qaghaaR-kFdJve7WtqFvpk
port: 3000
name: offline_pink
colorize_logging: true
host: 0.0.0.0
port_reuse: false
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
session:
  key: amber.session
  store: signed_cookie
  expires: 0

database_url: postgres://localhost:5432/offline_pink_development
secrets:
  description: Store your development secrets credentials and settings here.

