secret_key_base: 2LMqiWnO_adAJy6kaFZZ2qaghaaR-kFdJve7WtqFvpk
port: 3000
name: offline_pink
colorize_logging: true
host: 0.0.0.0
port_reuse: false
process_count: 1
redis_url: "redis://localhost:6379"
session:
  key: amber.session
  store: signed_cookie
  expires: 0

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  context:
    - request
    - params

database_url: postgres://localhost:5432/offline_pink_development

secrets:
  description: Store your development secrets credentials and settings here.

