secret_key_base: QcwfjmlsPPtHCiTq3DgCXom9eubVnxI18t019IZPsMw
port: 3000
name: offline_pink
colorize_logging: true
host: 0.0.0.0
port_reuse: false
process_count: 1
redis_url: "redis://localhost:6379"
session:
  key: amber.session
  store: signed_cookie
  expires: 0

database_url: postgres://postgres:@pg:5432/offline_pink_development
secrets:
  description: Store your development secrets credentials and settings here.
