# fly.toml file generated for summer-surf-4263 on 2022-06-02T07:47:42-06:00

app = "summer-surf-4263"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
